#!/bin/bash
# Autogenerated script for MC Panel

ABSOLUTE_PLAYIT_PATH=/home/user/painel-minecraft_V5/playit-linux-amd64

chmod +x "$ABSOLUTE_PLAYIT_PATH"

echo "Starting playit.gg tunnel..."
"$ABSOLUTE_PLAYIT_PATH" > /dev/null 2>&1 &
PLAYIT_PID=$!

trap 'echo "Stopping server and playit.gg tunnel..."; kill $PLAYIT_PID; exit' SIGINT SIGTERM

echo "Waiting for tunnel..."
sleep 5

echo "Starting Minecraft server..."
nix-shell -p pkgs.jdk21_headless --run "java -Xms12G -Xmx12G -jar purpur-1.21.11.jar nogui"
